export interface WordList {
    label: string;
    value: string;
    words: string[];
}

const initialSelectedWordList: WordList = {
    label: "Please select a word list",
    value: "",
    words: [],
};

export const german10: WordList = {
    label: "German 10",
    value: "german10",
    words: [
        "Affe",
        "Banane",
        "Clown",
        "Dusche",
        "Eichhoernchen",
        "Fisch",
        "Geschenk",
        "Haus",
        "Igel",
        "Junge",
    ],
};

export const german20: WordList = {
    label: "German 20",
    value: "german20",
    words: [
        "Affe",
        "Banane",
        "Clown",
        "Dusche",
        "Eichhoernchen",
        "Fisch",
        "Geschenk",
        "Haus",
        "Igel",
        "Junge",
        "Katz",
        "Lama",
        "Mann",
        "Nase",
        "Ochse",
        "Pferd",
    ],
};

export const german100: WordList = {
    label: "German 100",
    value: "german100",
    words: [
        "Auto",
        "Affe",
        "Fahrrad",
        "Burg",
        "Computer",
        "Handy",
        "Baum",
        "Astronaut",
        "Tisch",
        "Stuhl",
        "Buch",
        "Schule",
        "Universität",
        "Haus",
        "Wohnung",
        "Zug",
        "Flugzeug",
        "Schiff",
        "Boot",
        "Bus",
        "Straße",
        "Brücke",
        "Tunnel",
        "Berg",
        "Fluss",
        "See",
        "Meer",
        "Ozean",
        "Wald",
        "Park",
        "Garten",
        "Blume",
        "Baum",
        "Hund",
        "Katze",
        "Vogel",
        "Fisch",
        "Pferd",
        "Kuh",
        "Schwein",
        "Schaf",
        "Ziege",
        "Huhn",
        "Ente",
        "Gans",
        "Elefant",
        "Löwe",
        "Tiger",
        "Bär",
        "Giraffe",
        "Nashorn",
        "Hippopotamus",
        "Krokodil",
        "Schlange",
        "Spinne",
        "Insekt",
        "Schmetterling",
        "Biene",
        "Ameise",
        "Käfer",
        "Wurm",
        "Kuchen",
        "Brot",
        "Käse",
        "Milch",
        "Wasser",
        "Saft",
        "Kaffee",
        "Tee",
        "Bier",
        "Wein",
        "Schnaps",
        "Limonade",
        "Schokolade",
        "Bonbon",
        "Eis",
        "Suppe",
        "Salat",
        "Pizza",
        "Burger",
        "Sushi",
        "Steak",
        "Pommes",
        "Nudeln",
        "Reis",
        "Gemüse",
        "Obst",
        "Apfel",
        "Birne",
        "Banane",
        "Orange",
        "Zitrone",
        "Kirsche",
        "Erdbeere",
        "Himbeere",
        "Blaubeere",
        "Traube",
        "Melone",
        "Pfirsich",
        "Pflaume",
        "Mango",
        "Ananas",
        "Kokosnuss",
    ],
};

export const animals100: WordList = {
    label: "Animal 100",
    value: "animals100",
    words: [
        "Hund",
        "Katze",
        "Elefant",
        "Giraffe",
        "Löwe",
        "Tiger",
        "Bär",
        "Affe",
        "Hai",
        "Wal",
        "Delphin",
        "Pinguin",
        "Adler",
        "Falke",
        "Papagei",
        "Schmetterling",
        "Käfer",
        "Spinne",
        "Ameise",
        "Biene",
        "Schlange",
        "Krokodil",
        "Alligator",
        "Schildkröte",
        "Echse",
        "Frosch",
        "Kröte",
        "Maus",
        "Ratte",
        "Hamster",
        "Kaninchen",
        "Meerschweinchen",
        "Pferd",
        "Esel",
        "Kamel",
        "Zebra",
        "Nashorn",
        "Hippopotamus",
        "Gorilla",
        "Orang-Utan",
        "Känguru",
        "Koala",
        "Wombat",
        "Erdmännchen",
        "Faultier",
        "Dachs",
        "Otter",
        "Igel",
        "Maulwurf",
        "Waschbär",
        "Wolf",
        "Fuchs",
        "Luchs",
        "Elch",
        "Rentier",
        "Antilope",
        "Gazelle",
        "Gnu",
        "Büffel",
        "Giraffenaffe",
        "Flamingo",
        "Storch",
        "Pelikan",
        "Schwan",
        "Reiher",
        "Kolibri",
        "Spatz",
        "Amsel",
        "Drossel",
        "Star",
        "Kuckuck",
        "Eule",
        "Geier",
        "Milan",
        "Möwe",
        "Albatros",
        "Seeadler",
        "Tukan",
        "Fasan",
        "Truthahn",
        "Huhn",
        "Ente",
        "Gans",
        "Taube",
        "Pfau",
        "Goldfisch",
        "Karpfen",
        "Forelle",
        "Lachs",
        "Hecht",
        "Barsch",
        "Zander",
        "Thunfisch",
        "Schwertfisch",
        "Rochen",
    ],
};

export const historyPersonalities: WordList = {
    label: "Personalities in the history of mankind",
    value: "historyPersonalities",
    words: [
        "Mohammed",
        "Isaac Newton",
        "Jesus von Nazaret",
        "Buddha",
        "Johannes Gutenberg",
        "Christoph Kolumbus",
        "Albert Einstein	",
        "Galileo Galilei	",
        "Aristoteles",
        "Mose",
        "Charles Darwin",
        "Martin Luther",
        "George Washington",
        "Karl Marx",
        "Dschingis Khan",
        "William Shakespeare",
        "Thomas Alva Edison",
        "Adolf Hitler",
        "Ludwig van Beethoven",
        "Henry Ford",
        "Carl Benz",
        "Bill Gates",
        "Wolfgang Amadeus Mozart",
        "Kleopatra",
    ],
};

export const celebreties: WordList = {
    label: "Celebreties",
    value: "celebreties",
    words: [
        "Beyoncé",
        "Cristiano Ronaldo",
        "Taylor Swift",
        "LeBron James",
        "Rihanna",
        "Roger Federer",
        "Lady Gaga",
        "Lionel Messi",
        "Angelina Jolie",
        "Justin Bieber",
        "Serena Williams",
        "Kim Kardashian",
        "Brad Pitt",
        "Adele",
        "Stephen Curry",
        "Katy Perry",
        "Tom Cruise",
        "Jennifer Lopez",
        "Ellen DeGeneres",
        "Oprah Winfrey",
        "Dwayne Johnson",
        "Ed Sheeran",
        "Emma Watson",
        "Robert Downey Jr.",
        "Ariana Grande",
        "Chris Hemsworth",
        "Selena Gomez",
        "Michael Jordan",
        "Jennifer Aniston",
        "David Beckham",
        "Kanye West",
        "Scarlett Johansson",
        "Drake",
        "Virat Kohli",
        "Meryl Streep",
        "Bruno Mars",
        "Tiger Woods",
        "Billie Eilish",
        "Elon Musk",
        "Vin Diesel",
        "Leonardo DiCaprio",
        "Sandra Bullock",
        "Shawn Mendes",
        "Usain Bolt",
        "Harry Styles",
        "Taylor Lautner",
        "Will Smith",
        "Johnny Depp",
        "Eminem",
        "Gigi Hadid",
        "Daniel Radcliffe",
        "Chris Evans",
        "Keanu Reeves",
        "Kylie Jenner",
        "The Weeknd",
        "Natalie Portman",
        "Hugh Jackman",
        "Cardi B",
        "J.K. Rowling",
        "Novak Djokovic",
        "Shakira",
        "Tom Hanks",
        "Charlize Theron",
        "Ryan Reynolds",
        "Travis Scott",
        "Anne Hathaway",
        "Mark Zuckerberg",
        "Zac Efron",
        "Kristen Stewart",
        "Nicki Minaj",
        "Lewis Hamilton",
        "Jimmy Fallon",
        "Gal Gadot",
        "Sofia Vergara",
        "Jason Statham",
        "Emma Stone",
        "Celine Dion",
        "Pink",
        "Denzel Washington",
        "Camila Cabello",
        "Samuel L. Jackson",
        "Simon Cowell",
        "Miley Cyrus",
        "Gordon Ramsay",
        "Michael Phelps",
        "Chris Pratt",
        "Blake Lively",
        "Timothee Chalamet",
        "Margot Robbie",
    ],
};

export const moviesAndShows: WordList = {
    label: "Movies & Shows",
    value: "moviesAndShows",
    words: [
        "Der Pate",
        "Star Wars: Eine neue Hoffnung",
        "Titanic",
        "Jurassic Park",
        "Forrest Gump",
        "Der Herr der Ringe: Die Gefährten",
        "Der Zauberer von Oz",
        "Schindlers Liste",
        "E.T. – Der Außerirdische",
        "Avatar – Aufbruch nach Pandora",
        "Der weiße Hai",
        "Inception",
        "Fight Club",
        "Pulp Fiction",
        "Matrix",
        "Zurück in die Zukunft",
        "Indiana Jones: Jäger des verlorenen Schatzes",
        "Der Dunkle Ritter",
        "Harry Potter und der Stein der Weisen",
        "Game of Thrones",
        "Breaking Bad",
        "Friends",
        "Die Sopranos",
        "Stranger Things",
        "The Big Bang Theory",
        "The Simpsons",
        "House of Cards",
        "Sherlock",
        "Lost",
        "The Office (US)",
        "The Crown",
        "Black Mirror",
        "Doctor Who",
        "Dexter",
        "Mad Men",
        "The Walking Dead",
        "The Mandalorian",
        "Grey's Anatomy",
        "Twin Peaks",
    ],
};

export const wordLists: WordList[] = [
    initialSelectedWordList,
    german10,
    german20,
    german100,
    animals100,
    historyPersonalities,
    celebreties,
];
